In [14]:
!pip install --upgrade pip

  Using cached pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Accès refusé: 'C:\\Users\\Lam & Rodrigues\\AppData\\Local\\Temp\\pip-uninstall-3xajkjp5\\pip.exe'
Consider using the `--user` option or check the permissions.



In [6]:
!pip install pandas numpy

'which' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.


In [15]:
!which python3

'which' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.


In [17]:
import numpy as np

In [18]:
l = [i for i in range(10)]

In [23]:
ar = np.array(l)

In [24]:
ar.mean()

4.5

In [25]:
ar.std()

2.8722813232690143

In [29]:
ex = list([1, 2, 3, 's'])
ex2 = [1, 2, 3, 's']

In [30]:
np.array(ex)

array(['1', '2', '3', 's'], dtype='<U11')

In [31]:
m = np.array([[1,2], [3,4]])

In [32]:
m[0][1]

2

In [33]:
m

array([[1, 2],
       [3, 4]])

In [34]:
m.shape

(2, 2)

In [36]:
m*m

array([[ 1,  4],
       [ 9, 16]])

In [37]:
m2 = np.array([1, 2, 3, 4, 5], ndmin=2); m2

array([[1, 2, 3, 4, 5]])

In [38]:
m2.shape

(1, 5)

In [39]:
m2.shape = (5,1)

In [40]:
m2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [41]:
m2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [42]:
b = np.linspace(0, 2, 4)

In [43]:
b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [46]:
b**2

array([0.        , 0.44444444, 1.77777778, 4.        ])

In [49]:
c = np.arange(24).reshape(2, 3, 4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
c.shape

(2, 3, 4)

In [52]:
c.ndim

3

In [54]:
ar = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
#lignes 2 et 3 
#et colonnes 1 et 2
ar[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [60]:
#juste la 2e ligne et un tableau à une dimension
ar[1,:]

array([4, 5, 6])

In [61]:
#la dernière colonne
ar[:,1]

array([2, 5, 8])

In [62]:
s = "personne ecoute ce que je raconte"

In [63]:
s[0:9]

'personne '

In [64]:
ar==2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [66]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [67]:
A+B

array([[3, 1],
       [3, 5]])

In [68]:
a = np.array([1.7, 2.8, 3])

In [69]:
a.argmax()

2

In [70]:
b = np.array([[1,2], [3,4]]); b

array([[1, 2],
       [3, 4]])

In [71]:
b.sum(axis=0)

array([4, 6])

In [72]:
b.sum(axis=1)

array([3, 7])

In [73]:
np.array([1,2,3,4]).cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.tile(3,8) #tableau de 8 éléments
#les éléments sont : 2

array([3, 3, 3, 3, 3, 3, 3, 3])

In [77]:
z = np.zeros((2, 4)); z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
z.dtype

dtype('float64')

In [79]:
6 * z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.ones((2, 4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [81]:
np.diag(np.array([1,4]))

array([[1, 0],
       [0, 4]])

In [1]:
##Q1

In [2]:
#import numpy as np

In [4]:
##Q2

Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640


In [5]:
#!python3 -c "import numpy; print(numpy.__version__)"

In [6]:
##Q3

In [7]:
#l = [i for i in range(10)]
#vec = np.array(l)

In [1]:
##Q4

In [2]:
#

In [3]:
##Q5

In [4]:
#Z = np.arange(10,51)

In [5]:
##Q6

In [6]:
#Z[::-1]

In [7]:
##Q7

In [9]:
#matrice = np.array([[0, 0, 0], [2, 8, 5], [6, 7 ,8]])

In [10]:
##Q8

In [11]:
#md = np.diag(np.array([1, 1, 1]))

In [12]:
##Q9

In [13]:
#mr = np.random.rand(3, 3)

In [14]:
##Q10

In [15]:
#mrr = np.random.rand(10, 10);
#mrr.max()

In [16]:
##Q11

In [17]:
#mrrr = np.array([1, 2, 3, 4])
#np.diag(mrrr, -1)

In [19]:
##Q12

In [20]:
#list = np.sum(np.random.rand(5))

In [21]:
##Q13

In [22]:
#list = np.mean(np.random.rand(5))

In [23]:
##Q14

In [24]:
#def sumTab (tableau) :
#    print(len(tableau))

In [25]:
##Q15

In [26]:
#tab = np.random.rand(10)